absolute: true  # Force absolute comparison for cardboardlint
project:
  name: iodata
  requirements: [
    [sympy, sympy],
    # pylint 2.11.* seems to have bugs which break the CI.
    ["pylint <2.11.0", "pylint<2.11.0"]
  ]
  packages:
    - dist_name: qc-iodata
      tools:
        - write-py-version
        - cardboardlint-static
        - build-py-inplace
        - cardboardlint-dynamic
        - pytest
        - upload-codecov
        - build-sphinx-doc
        - upload-docs-gh
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        - deploy-github
